### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by stickylab** [leonjovanovic/water-shader-unity#3]
![image](https://user-images.githubusercontent.com/87752832/213094832-801c7285-cd3f-41c1-9e55-7e35d532b2a7.png)
just tried and failed

**Comment by leonjovanovic** [comment]
It should be working now. Can you please check?

**Comment by stickylabdev** [comment]
ill check later

**Comment by stickylab** [comment]
![image](https://user-images.githubusercontent.com/87752832/213173949-31f8d8eb-e240-49ae-aca9-27f4180ee967.png)

 

just tried in for the first time ...how to change the color ?

**Comment by stickylab** [comment]
![Uploading image.png…]()
 how to change the black to brown ?

**Comment by stickylab** [comment]
![image](https://user-images.githubusercontent.com/87752832/213178870-9bfe0ee2-3180-4be9-bceb-e34c2282f7cd.png)

**Comment by leonjovanovic** [comment]
> ![image](https://user-images.githubusercontent.com/87752832/213173949-31f8d8eb-e240-49ae-aca9-27f4180ee967.png)
> 
> just tried in for the first time ...how to change the color ?

What are you trying to do? Should be transparent blue when you load the scene.

**Comment by leonjovanovic** [comment]
> Uploading image.png…
> how to change the black to brown ?

Change PoolWaterDirectional or PoolWaterDistortional inside Assets/Materials/Pool folder. Change Main color (as well as alpha (transparency), Fog color and Fog density.

**Comment by stickylab** [comment]
i am trying to make 
![image](https://user-images.githubusercontent.com/87752832/213373420-67c83443-f58a-4856-9a03-ce9d85e78a9a.png)
 
dirty water

**Comment by stickylab** [comment]
![image](https://user-images.githubusercontent.com/87752832/213377295-c07e6ae4-d811-4e57-9638-af7c2c248990.png)
tobe honest this is frustating

**Comment by leonjovanovic** [comment]
> Change PoolWaterDirectional or PoolWaterDistortional inside Assets/Materials/Pool folder. Change Main color (as well as alpha (transparency), Fog color and Fog density.

You are not following instructions and therefore its not working as expected. Read again, if you want to change color, you need to change actual Material in path above or create new Material.

**Comment by stickylabdev** [comment]
I followwd the i structure but the objects not follow me

Pada tanggal Jum, 20 Jan 2023 19.15, Leon Jovanovic <
***@***.***> menulis:

**Comment by leonjovanovic** [comment]
![image](https://user-images.githubusercontent.com/45070620/213726414-ffdfb95b-359a-428a-a221-675ed75a7085.png)

**Comment by stickylabdev** [comment]
Thanks a lot sir

Pada tanggal Jum, 20 Jan 2023 21.45, Leon Jovanovic <
***@***.***> menulis:

**Comment by stickylabdev** [comment]
Maybe its because our unity version is diferent

Pada tanggal Jum, 20 Jan 2023 23.38, Muafakul Khoir ***@***.***>
menulis:

**Comment by stickylab** [comment]
![image](https://user-images.githubusercontent.com/87752832/213759223-2ae07942-5faa-4645-a0b2-d7109e45e8f3.png)

100% same setting ,with difeerent result

**Comment by leonjovanovic** [comment]
Dont change Material in Water object setting. Based on your picture, you selected water and changes settings of material from Inspector. You need to Click on material from Pool folder and change settings there.
